### ISSUE TITLE
Misspelling words in README

### ISSUE THREAD

**Issue by abrahamduran** [EvsenevDev/VIPERModuleTemplate#2]
Hi, awesome work! This for sure makes it easier to start with VIPER. I love it.

I read your README.

Some are: shound, compete, inpurt, Presener

If you don't mind, I could open a PR for this.

**Comment by EvsenevDev** [comment]
@abrahamduran yes, PRs is cool! 👍

**Comment by EvsenevDev** [comment]
Updated in PR #3
